/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	__webpack_require__(1)
	__webpack_require__(5)
	__webpack_require__(9)
	__webpack_require__(13)
	__webpack_require__(17)
	var __weex_template__ = __webpack_require__(21)
	var __weex_style__ = __webpack_require__(22)
	var __weex_script__ = __webpack_require__(23)

	__weex_define__('@weex-component/5963664bb2f19dce71a6e8bd54e12861', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})

	__weex_bootstrap__('@weex-component/5963664bb2f19dce71a6e8bd54e12861',undefined,undefined)

/***/ },
/* 1 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(2)
	var __weex_style__ = __webpack_require__(3)
	var __weex_script__ = __webpack_require__(4)

	__weex_define__('@weex-component/bullet', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})


/***/ },
/* 2 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "style": {
	    "left": function () {return this.left},
	    "bottom": function () {return this.bottom}
	  },
	  "classList": function () {return [this.classname]},
	  "children": [
	    {
	      "type": "image",
	      "attr": {
	        "src": function () {return this.imgurl}
	      },
	      "style": {
	        "width": 45,
	        "height": 45
	      }
	    }
	  ]
	}

/***/ },
/* 3 */
/***/ function(module, exports) {

	module.exports = {
	  "show": {
	    "position": "fixed",
	    "opacity": 1
	  },
	  "hide": {
	    "position": "fixed",
	    "opacity": 0
	  }
	}

/***/ },
/* 4 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	module.exports = {
	  data: function () {return {
	    backcolor: 'black',
	    left: '',
	    bottom: '',
	    classname: '',
	    imgurl: ''
	  }}
	};}
	/* generated by weex-loader */


/***/ },
/* 5 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(6)
	var __weex_style__ = __webpack_require__(7)
	var __weex_script__ = __webpack_require__(8)

	__weex_define__('@weex-component/enermy-plane', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})


/***/ },
/* 6 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "id": "test",
	  "style": {
	    "left": function () {return this.left},
	    "bottom": function () {return this.bottom},
	    "height": function () {return this.height}
	  },
	  "attr": {
	    "index": function () {return this.index}
	  },
	  "classList": [
	    "show"
	  ],
	  "children": [
	    {
	      "type": "image",
	      "attr": {
	        "src": function () {return this.imgurl}
	      },
	      "style": {
	        "width": 50,
	        "height": function () {return this.height}
	      }
	    }
	  ]
	}

/***/ },
/* 7 */
/***/ function(module, exports) {

	module.exports = {
	  "show": {
	    "position": "fixed",
	    "width": 50,
	    "opacity": 1
	  },
	  "hide": {
	    "width": 50,
	    "position": "fixed",
	    "opacity": 1
	  }
	}

/***/ },
/* 8 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	var animation = __weex_require__('@weex-module/animation');
	module.exports = {
	  data: function () {return {
	    imgurl: '',
	    img: '',
	    color: 'black',
	    left: '',
	    bottom: '',
	    index: '',
	    type: '',
	    height: ''
	  }},
	  ready: function ready() {
	    if (this.type == 0) {
	      this.imgurl = this.img[2];
	      this.height = 50;
	    } else if (this.type == 1) {
	      this.imgurl = this.img[3];
	      this.height = 70;
	    } else if (this.type == 2) {
	      this.imgurl = this.img[4];
	      this.height = 50;
	    } else {
	      this.imgurl = this.img[5];
	      this.height = 50;
	    }
	    this.$on('hit', function (e) {
	      if (this.type !== 3) this.imgurl = this.img[6];else {
	          this.imgurl = this.img[7];
	        }
	      var testEl = this.$el('test');
	      animation.transition(testEl, {
	        styles: {
	          opacity: 0
	        },
	        duration: 2000,
	        delay: 0 });
	    });
	  }
	};}
	/* generated by weex-loader */


/***/ },
/* 9 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(10)
	var __weex_style__ = __webpack_require__(11)
	var __weex_script__ = __webpack_require__(12)

	__weex_define__('@weex-component/myplane', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})


/***/ },
/* 10 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "id": "test",
	  "style": {
	    "left": function () {return this.left},
	    "bottom": function () {return this.bottom}
	  },
	  "classList": function () {return [this.classname]},
	  "children": [
	    {
	      "type": "image",
	      "attr": {
	        "src": function () {return this.control?this.img[0]:this.img[1]}
	      },
	      "style": {
	        "width": 80,
	        "height": 80
	      }
	    }
	  ]
	}

/***/ },
/* 11 */
/***/ function(module, exports) {

	module.exports = {
	  "show": {
	    "position": "fixed",
	    "opacity": 1
	  },
	  "hide": {
	    "position": "fixed",
	    "bottom": 10,
	    "opacity": 1
	  }
	}

/***/ },
/* 12 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	var animation = __weex_require__('@weex-module/animation');
	module.exports = {
	  data: function () {return {
	    classname: '',
	    img: '',
	    color: 'black',
	    left: '',
	    bottom: '',
	    control: true
	  }},
	  ready: function ready() {
	    this.$on('explore', function () {
	      this.control = false;
	      var testEl = this.$el('test');
	      animation.transition(testEl, {
	        styles: {
	          opacity: 0
	        },
	        duration: 2000,
	        delay: 0 });
	      setTimeout(function () {
	        this.control = true;
	        var testEl = this.$el('test');
	        animation.transition(testEl, {
	          styles: {
	            opacity: 1
	          },
	          duration: 2000,
	          delay: 0 });
	      }.bind(this), 2000);
	    }.bind(this));
	  }
	};}
	/* generated by weex-loader */


/***/ },
/* 13 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(14)
	var __weex_style__ = __webpack_require__(15)
	var __weex_script__ = __webpack_require__(16)

	__weex_define__('@weex-component/modelselect', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})


/***/ },
/* 14 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "id": "dialog",
	  "classList": [
	    "dialog"
	  ],
	  "children": [
	    {
	      "type": "image",
	      "attr": {
	        "src": "http://ww2.sinaimg.cn/large/006jSeDEjw1fb2um05zw1j30ei0lrag3.jpg",
	        "resize": "cover"
	      },
	      "style": {
	        "width": 750,
	        "height": 1350,
	        "position": "fixed",
	        "left": 0,
	        "top": 0
	      }
	    },
	    {
	      "type": "image",
	      "attr": {
	        "src": "http://ww2.sinaimg.cn/large/006jSeDEjw1fb2ule7bicj305o066wh9.jpg",
	        "resize": "cover"
	      },
	      "style": {
	        "width": 300,
	        "height": 300,
	        "position": "fixed",
	        "left": 40,
	        "top": 600
	      },
	      "events": {
	        "touchstart": "model1selected"
	      }
	    },
	    {
	      "type": "image",
	      "attr": {
	        "src": "http://ww4.sinaimg.cn/large/006jSeDEjw1fb2uloprs8j309d06w40u.jpg",
	        "resize": "cover"
	      },
	      "style": {
	        "width": 300,
	        "height": 300,
	        "position": "fixed",
	        "right": 40,
	        "top": 600
	      },
	      "events": {
	        "touchstart": "model2selected"
	      }
	    },
	    {
	      "type": "text",
	      "style": {
	        "fontSize": 40,
	        "color": "#FFFFFF",
	        "position": "fixed",
	        "left": 80,
	        "top": 930
	      },
	      "events": {
	        "touchstart": "handlemodel1"
	      },
	      "attr": {
	        "value": "酷炫模式"
	      }
	    },
	    {
	      "type": "text",
	      "style": {
	        "fontSize": 40,
	        "color": "#FFFFFF",
	        "position": "fixed",
	        "right": 80,
	        "top": 930
	      },
	      "events": {
	        "touchstart": "handlemodel2"
	      },
	      "attr": {
	        "value": "小清新模式"
	      }
	    }
	  ]
	}

/***/ },
/* 15 */
/***/ function(module, exports) {

	module.exports = {
	  "dialog": {
	    "position": "fixed",
	    "top": 0,
	    "right": 0,
	    "bottom": 0,
	    "left": 0
	  }
	}

/***/ },
/* 16 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	module.exports = {
	  data: function () {return {}},
	  methods: {
	    model1selected: function model1selected() {
	      this._parent.$emit('model1selected');
	    },
	    model2selected: function model2selected() {
	      this._parent.$emit('model2selected');
	    }
	  }
	};}
	/* generated by weex-loader */


/***/ },
/* 17 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(18)
	var __weex_style__ = __webpack_require__(19)
	var __weex_script__ = __webpack_require__(20)

	__weex_define__('@weex-component/rank', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})


/***/ },
/* 18 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "classList": [
	    "rank"
	  ],
	  "children": [
	    {
	      "type": "text",
	      "classList": [
	        "text"
	      ],
	      "attr": {
	        "value": function () {return this.index+1}
	      }
	    },
	    {
	      "type": "text",
	      "classList": [
	        "text"
	      ],
	      "attr": {
	        "value": function () {return this.name}
	      }
	    },
	    {
	      "type": "text",
	      "classList": [
	        "text"
	      ],
	      "attr": {
	        "value": function () {return this.score}
	      }
	    }
	  ]
	}

/***/ },
/* 19 */
/***/ function(module, exports) {

	module.exports = {
	  "rank": {
	    "paddingTop": 20,
	    "paddingBottom": 20,
	    "paddingLeft": 100,
	    "paddingRight": 100,
	    "flexDirection": "row",
	    "justifyContent": "space-between"
	  },
	  "text": {
	    "textAlign": "center",
	    "fontSize": 40,
	    "color": "#FFA500"
	  }
	}

/***/ },
/* 20 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	module.exports = {
	  data: function () {return {
	    index: '',
	    score: '',
	    name: ''
	  }}
	};}
	/* generated by weex-loader */


/***/ },
/* 21 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "classList": [
	    "game-board"
	  ],
	  "events": {
	    "panmove": "handlepanmove"
	  },
	  "children": [
	    {
	      "type": "video",
	      "classList": [
	        "video"
	      ],
	      "events": {
	        "finish": "onfinish",
	        "fail": "video_fail"
	      },
	      "attr": {
	        "playStatus": function () {return this.video.play_video},
	        "src": function () {return this.selectedurl[11]}
	      },
	      "style": {
	        "width": 750,
	        "height": 1
	      }
	    },
	    {
	      "type": "div",
	      "children": [
	        {
	          "type": "image",
	          "attr": {
	            "src": function () {return this.selectedurl[9]},
	            "resize": "cover"
	          },
	          "id": "target",
	          "style": {
	            "width": 750,
	            "height": 1400,
	            "position": "fixed",
	            "left": 0,
	            "bottom": function () {return this.backimgtop+1395+1395}
	          }
	        },
	        {
	          "type": "image",
	          "attr": {
	            "src": "http://ww2.sinaimg.cn/large/006jSeDEjw1fbdpybija3j307v0e0gm9.jpg",
	            "resize": "cover"
	          },
	          "id": "target",
	          "style": {
	            "width": 750,
	            "height": 1400,
	            "position": "fixed",
	            "left": 0,
	            "bottom": function () {return this.backimgtop+1395}
	          }
	        },
	        {
	          "type": "image",
	          "attr": {
	            "src": function () {return this.selectedurl[9]},
	            "resize": "cover"
	          },
	          "id": "target",
	          "style": {
	            "width": 750,
	            "height": 1400,
	            "position": "fixed",
	            "left": 0,
	            "bottom": function () {return this.backimgtop}
	          }
	        }
	      ]
	    },
	    {
	      "type": "div",
	      "classList": [
	        "jindutiao"
	      ],
	      "style": {
	        "width": function () {return this.oil.left},
	        "backgroundColor": function () {return this.oil.color},
	        "position": "fixed",
	        "top": 0,
	        "left": 0
	      }
	    },
	    {
	      "type": "bullet",
	      "repeat": {
	        "expression": function () {return this.bulletlist},
	        "key": "index",
	        "value": "item"
	      },
	      "attr": {
	        "trackBy": "index",
	        "left": function () {return this.item.left},
	        "bottom": function () {return this.item.bottom},
	        "classname": function () {return this.item.classname},
	        "imgurl": function () {return this.selectedurl[8]}
	      }
	    },
	    {
	      "type": "enermy-plane",
	      "repeat": {
	        "expression": function () {return this.enermylist},
	        "key": "index",
	        "value": "item"
	      },
	      "id": function () {return 'enermy-' + (this.item.index)},
	      "attr": {
	        "type": function () {return this.item.type},
	        "trackBy": "index",
	        "img": function () {return this.selectedurl},
	        "left": function () {return this.item.left},
	        "bottom": function () {return this.item.bottom},
	        "index": function () {return this.item.index},
	        "hit": function () {return this.item.hit}
	      }
	    },
	    {
	      "type": "myplane",
	      "id": "myplane",
	      "attr": {
	        "classname": function () {return this.myclassname},
	        "left": function () {return this.left},
	        "bottom": function () {return this.bottom},
	        "img": function () {return this.selectedurl.slice(0,2)}
	      }
	    },
	    {
	      "type": "image",
	      "id": "music",
	      "attr": {
	        "src": "http://ww2.sinaimg.cn/large/006jSeDEjw1fb2ulutlglj304m04labc.jpg",
	        "resize": "cover"
	      },
	      "style": {
	        "width": 60,
	        "height": 60,
	        "position": "fixed",
	        "right": 10,
	        "top": 10,
	        "opacity": function () {return (this.music.play===true)?1:0.5}
	      },
	      "events": {
	        "touchstart": "handlemusicclick"
	      }
	    },
	    {
	      "type": "image",
	      "id": "pause",
	      "attr": {
	        "src": "http://ww4.sinaimg.cn/large/006jSeDEjw1fb2ulx7nu3j305k05kwey.jpg"
	      },
	      "style": {
	        "width": 60,
	        "height": 60,
	        "position": "fixed",
	        "right": 10,
	        "top": 90
	      },
	      "events": {
	        "touchstart": "handlePause"
	      }
	    },
	    {
	      "type": "image",
	      "id": "rank",
	      "attr": {
	        "src": "http://ww4.sinaimg.cn/large/006jSeDEjw1fbdq9r2fnkj30280293yn.jpg"
	      },
	      "style": {
	        "width": 60,
	        "height": 60,
	        "position": "fixed",
	        "right": 10,
	        "top": 170
	      },
	      "events": {
	        "touchstart": "handleRank"
	      }
	    },
	    {
	      "type": "div",
	      "classList": [
	        "addscore"
	      ],
	      "id": "addscore",
	      "style": {
	        "bottom": function () {return this.addscorebottom},
	        "left": function () {return this.addscoreleft}
	      },
	      "children": [
	        {
	          "type": "text",
	          "style": {
	            "fontSize": 30,
	            "color": "#FFFFFF"
	          },
	          "attr": {
	            "value": function () {return '+' + (this.addscore)}
	          }
	        }
	      ]
	    },
	    {
	      "type": "div",
	      "classList": [
	        "score"
	      ],
	      "children": [
	        {
	          "type": "text",
	          "style": {
	            "fontSize": 30,
	            "color": "#FFFFFF"
	          },
	          "attr": {
	            "value": function () {return 'Score: ' + (this.score)}
	          }
	        },
	        {
	          "type": "text",
	          "style": {
	            "fontSize": 30,
	            "color": "#FFFFFF"
	          },
	          "attr": {
	            "value": function () {return this.status}
	          }
	        }
	      ]
	    },
	    {
	      "type": "div",
	      "id": "dialog",
	      "classList": [
	        "dialog"
	      ],
	      "shown": function () {return this.isShowDialog},
	      "children": [
	        {
	          "type": "div",
	          "classList": [
	            "dialog-backdrop"
	          ]
	        },
	        {
	          "type": "image",
	          "attr": {
	            "src": function () {return this.selectedurl[10]}
	          },
	          "style": {
	            "width": 700,
	            "height": 450,
	            "position": "absolute",
	            "left": 25,
	            "top": 325
	          }
	        },
	        {
	          "type": "div",
	          "classList": [
	            "dialog-content"
	          ],
	          "children": [
	            {
	              "type": "div",
	              "classList": [
	                "dialog-header"
	              ],
	              "children": [
	                {
	                  "type": "text",
	                  "classList": [
	                    "dialog-title"
	                  ],
	                  "style": {
	                    "fontSize": 60,
	                    "color": "#FFA500"
	                  },
	                  "attr": {
	                    "value": function () {return (this.status==='init')?this.dialog.init.header:(this.status==='pause')?this.dialog.pause.header:this.dialog.die.header}
	                  }
	                }
	              ]
	            },
	            {
	              "type": "div",
	              "classList": [
	                "dialog-body"
	              ],
	              "shown": function () {return this.status!=='init'},
	              "children": [
	                {
	                  "type": "text",
	                  "style": {
	                    "fontSize": 40,
	                    "color": "#FFA500"
	                  },
	                  "attr": {
	                    "value": function () {return '当前得分：' + (this.score)}
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "fontSize": 30,
	                    "color": "#FFA500"
	                  },
	                  "shown": function () {return this.dialog.die.reason===1},
	                  "attr": {
	                    "value": "小心敌机"
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "fontSize": 30,
	                    "color": "#FFA500"
	                  },
	                  "shown": function () {return this.dialog.die.reason===2},
	                  "attr": {
	                    "value": "不吃披萨会燃油耗尽哦"
	                  }
	                }
	              ]
	            },
	            {
	              "type": "div",
	              "classList": [
	                "dialog-footer"
	              ],
	              "shown": function () {return this.status==='init'},
	              "children": [
	                {
	                  "type": "text",
	                  "classList": [
	                    "controlinfro"
	                  ],
	                  "events": {
	                    "touchstart": "handleStart"
	                  },
	                  "attr": {
	                    "value": "start"
	                  }
	                },
	                {
	                  "type": "text",
	                  "classList": [
	                    "controlinfro"
	                  ],
	                  "events": {
	                    "touchstart": "closeDialog"
	                  },
	                  "attr": {
	                    "value": "back"
	                  }
	                }
	              ]
	            },
	            {
	              "type": "div",
	              "classList": [
	                "dialog-footer"
	              ],
	              "shown": function () {return this.status==='pause'},
	              "children": [
	                {
	                  "type": "text",
	                  "classList": [
	                    "controlinfro"
	                  ],
	                  "events": {
	                    "touchstart": "handleStart"
	                  },
	                  "attr": {
	                    "value": "continue"
	                  }
	                },
	                {
	                  "type": "text",
	                  "classList": [
	                    "controlinfro"
	                  ],
	                  "events": {
	                    "touchstart": "closeDialog"
	                  },
	                  "attr": {
	                    "value": "back"
	                  }
	                }
	              ]
	            },
	            {
	              "type": "div",
	              "classList": [
	                "dialog-footer"
	              ],
	              "shown": function () {return this.status==='die'},
	              "children": [
	                {
	                  "type": "text",
	                  "classList": [
	                    "controlinfro"
	                  ],
	                  "events": {
	                    "touchstart": "handleStart"
	                  },
	                  "attr": {
	                    "value": "restart"
	                  }
	                },
	                {
	                  "type": "text",
	                  "classList": [
	                    "controlinfro"
	                  ],
	                  "events": {
	                    "touchstart": "closeDialog"
	                  },
	                  "attr": {
	                    "value": "back"
	                  }
	                }
	              ]
	            },
	            {
	              "type": "text",
	              "style": {
	                "fontSize": 25,
	                "color": "#FFA500",
	                "textAlign": "center",
	                "paddingTop": 80
	              },
	              "shown": function () {return this.status==='init'},
	              "attr": {
	                "value": "按start开始游戏，back返回上一级菜单"
	              }
	            }
	          ]
	        }
	      ]
	    },
	    {
	      "type": "modelselect",
	      "shown": function () {return this.showModel}
	    },
	    {
	      "type": "div",
	      "classList": [
	        "rank_model"
	      ],
	      "shown": function () {return this.showRank},
	      "children": [
	        {
	          "type": "div",
	          "classList": [
	            "dialog-backdrop"
	          ]
	        },
	        {
	          "type": "image",
	          "attr": {
	            "src": function () {return this.selectedurl[10]}
	          },
	          "style": {
	            "width": 720,
	            "height": 800,
	            "position": "absolute",
	            "left": 15,
	            "top": 120
	          }
	        },
	        {
	          "type": "div",
	          "classList": [
	            "rank_head"
	          ],
	          "children": [
	            {
	              "type": "text",
	              "classList": [
	                "text"
	              ],
	              "attr": {
	                "value": "排名"
	              }
	            },
	            {
	              "type": "text",
	              "classList": [
	                "text"
	              ],
	              "attr": {
	                "value": "用户名"
	              }
	            },
	            {
	              "type": "text",
	              "classList": [
	                "text"
	              ],
	              "attr": {
	                "value": "得分"
	              }
	            }
	          ]
	        },
	        {
	          "type": "div",
	          "classList": [
	            "rank_content"
	          ],
	          "children": [
	            {
	              "type": "text",
	              "shown": function () {return this.scores.length===0},
	              "style": {
	                "textAlign": "center",
	                "color": "#FFA500",
	                "fontSize": 40
	              },
	              "attr": {
	                "value": "还没有人玩过，排行榜上空空如也"
	              }
	            },
	            {
	              "type": "rank",
	              "repeat": {
	                "expression": function () {return this.scores},
	                "key": "index",
	                "value": "item"
	              },
	              "attr": {
	                "score": function () {return this.item},
	                "name": function () {return this.users[this.index]},
	                "index": function () {return this.index}
	              }
	            }
	          ]
	        },
	        {
	          "type": "div",
	          "classList": [
	            "rank_foot"
	          ],
	          "children": [
	            {
	              "type": "text",
	              "classList": [
	                "text"
	              ],
	              "events": {
	                "touchstart": "handleRankClear"
	              },
	              "attr": {
	                "value": "clearAll"
	              }
	            },
	            {
	              "type": "text",
	              "classList": [
	                "text"
	              ],
	              "events": {
	                "touchstart": "handleRankClose"
	              },
	              "attr": {
	                "value": "close"
	              }
	            }
	          ]
	        }
	      ]
	    }
	  ]
	}

/***/ },
/* 22 */
/***/ function(module, exports) {

	module.exports = {
	  "text": {
	    "textAlign": "center",
	    "fontSize": 40,
	    "color": "#FFA500"
	  },
	  "rank_model": {
	    "position": "fixed",
	    "top": 0,
	    "right": 0,
	    "bottom": 0,
	    "left": 0
	  },
	  "rank_content": {
	    "position": "absolute",
	    "top": 300,
	    "left": 25,
	    "width": 700
	  },
	  "rank_head": {
	    "position": "absolute",
	    "top": 200,
	    "left": 25,
	    "width": 700,
	    "height": 100,
	    "paddingTop": 20,
	    "paddingBottom": 20,
	    "paddingLeft": 100,
	    "paddingRight": 100,
	    "flexDirection": "row",
	    "justifyContent": "space-between"
	  },
	  "rank_foot": {
	    "position": "absolute",
	    "top": 740,
	    "left": 25,
	    "width": 700,
	    "height": 100,
	    "paddingTop": 20,
	    "paddingBottom": 20,
	    "paddingLeft": 100,
	    "paddingRight": 100,
	    "flexDirection": "row",
	    "justifyContent": "space-between"
	  },
	  "game-board": {
	    "width": 750,
	    "height": 1350
	  },
	  "video": {
	    "position": "absolute",
	    "top": 0,
	    "left": 0
	  },
	  "jindutiao": {
	    "position": "absolute",
	    "top": 0,
	    "left": 0,
	    "height": 5
	  },
	  "addscore": {
	    "width": 100,
	    "height": 50,
	    "position": "fixed",
	    "opacity": 1
	  },
	  "score": {
	    "position": "fixed",
	    "top": 10,
	    "left": 0
	  },
	  "dialog-backdrop": {
	    "opacity": 0.2,
	    "width": 750,
	    "height": 1350,
	    "backgroundColor": "#FFFFFF"
	  },
	  "dialog": {
	    "position": "fixed",
	    "top": 0,
	    "right": 0,
	    "bottom": 0,
	    "left": 0
	  },
	  "dialog-content": {
	    "width": 450,
	    "position": "absolute",
	    "top": 380,
	    "left": 150,
	    "textAlign": "center"
	  },
	  "dialog-header": {
	    "padding": 20,
	    "position": "relative",
	    "borderBottomWidth": 1,
	    "borderBottomStyle": "solid",
	    "borderBottomColor": "#efefef"
	  },
	  "dialog-body": {
	    "padding": 20,
	    "flexDirection": "column",
	    "justifyContent": "space-between"
	  },
	  "dialog-footer": {
	    "padding": 20,
	    "position": "relative",
	    "borderTopWidth": 1,
	    "borderTopStyle": "solid",
	    "borderTopColor": "#efefef",
	    "flexDirection": "row",
	    "justifyContent": "space-between"
	  },
	  "close": {
	    "fontSize": 60,
	    "position": "absolute",
	    "right": 10,
	    "top": 10
	  },
	  "btn": {
	    "textAlign": "center",
	    "color": "#ffffff",
	    "padding": 12,
	    "backgroundColor": "#3071a9",
	    "borderColor": "#285e8e",
	    "borderRadius": 4
	  },
	  "controlinfro": {
	    "fontSize": 45,
	    "color": "#FFA500"
	  }
	}

/***/ },
/* 23 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	var timer2;
	var timer;
	var index1 = 0;
	var index2 = 0;
	var temp = 0;var temp2 = 0;
	var storage = __weex_require__('@weex-module/storage');
	var modal = __weex_require__('@weex-module/modal');
	var key;
	var bubbleSort = function bubbleSort(arr, arr2) {
	  var flag = true;
	  var len = arr.length;
	  for (var i = 0; i < len - 1; i++) {
	    flag = true;
	    for (var j = 0; j < len - 1 - i; j++) {
	      if (arr[j] < arr[j + 1]) {
	        var temp = arr[j + 1];
	        arr[j + 1] = arr[j];
	        arr[j] = temp;
	        var temp = arr2[j + 1];
	        arr2[j + 1] = arr2[j];
	        arr2[j] = temp;
	        flag = false;
	      }
	    }
	    if (flag) {
	      break;
	    }
	  }
	};
	module.exports = {
	  data: function () {return {
	    a: ['http://ww1.sinaimg.cn/large/006jSeDEjw1fb2ulwmf2xj305k05k0uj.jpg', 'http://ww4.sinaimg.cn/large/006jSeDEjw1fb2ullafnoj305k055dhx.jpg', 'http://ww1.sinaimg.cn/large/006jSeDEjw1fb2uljr20lj305n04jta8.jpg', 'http://ww1.sinaimg.cn/large/006jSeDEjw1fb2uljezr1j305n0a0gpq.jpg', 'http://ww1.sinaimg.cn/large/006jSeDEjw1fb2ulk84frj305s04ctap.jpg', 'http://ww3.sinaimg.cn/large/006jSeDEjw1fb2ulxzanuj305v05s0uv.jpg', 'http://ww4.sinaimg.cn/large/006jSeDEjw1fb2ullafnoj305k055dhx.jpg', 'http://ww1.sinaimg.cn/large/006jSeDEjw1fbdpyc03j5j303f039t9e.jpg', 'http://ww1.sinaimg.cn/large/006jSeDEjw1fb2ulgt35tj302i03vglz.jpg', 'http://ww1.sinaimg.cn/large/006jSeDEjw1fbdpz73te8j30880emaaj.jpg', 'http://ww3.sinaimg.cn/large/006jSeDEjw1fb2ulynrfbj307c059gnn.jpg', 'http://gslb.miaopai.com/stream/iK8YPMJwHez-ot-OqVAWDA__.mp4?vend=miaopai&'],

	    b: ['http://ww2.sinaimg.cn/large/006jSeDEjw1fb2ulvxbmtj305t06jabg.jpg', 'http://ww1.sinaimg.cn/large/006jSeDEjw1fb2yfdk2bsj306806qtba.jpg', 'http://ww3.sinaimg.cn/large/006jSeDEjw1fb2y9lf174j305m040gmi.jpg', 'http://ww1.sinaimg.cn/large/006jSeDEjw1fb2y9m8o6vj302f023t8q.jpg', 'http://ww1.sinaimg.cn/large/006jSeDEjw1fb2ulnkvjtj305q05uq43.jpg', 'http://ww3.sinaimg.cn/large/006jSeDEjw1fb2ulxzanuj305v05s0uv.jpg', 'http://ww2.sinaimg.cn/large/006jSeDEjw1fb2y9mp6r5j305t05ognq.jpg', 'http://ww1.sinaimg.cn/large/006jSeDEjw1fbdpyc03j5j303f039t9e.jpg', 'http://ww2.sinaimg.cn/large/006jSeDEjw1fb2yd9v1g3j305t05sq4s.jpg', 'http://ww3.sinaimg.cn/large/006jSeDEjw1fb2ulshjr7j30xc0jx7ee.jpg', 'http://ww3.sinaimg.cn/large/006jSeDEjw1fb2ulcb9haj307204zaak.jpg', 'http://gslb.miaopai.com/stream/C3~hBqqtaSUsY6XpLA5xGA__.mp4?vend=miaopai&'],

	    selectedurl: [],
	    c: '',
	    showModel: true,
	    backimgtop: 0,
	    oil: {
	      left: 750,
	      color: 'orange'
	    },
	    dialog: {
	      init: {
	        header: "欢迎"
	      },
	      pause: {
	        header: "燃烧吧！少年"
	      },
	      die: {
	        header: "Game Over!",
	        reason: 0
	      }
	    },
	    status: 'init',
	    myclassname: 'show',
	    color1: 'orange',
	    left: 335,
	    bottom: 10,
	    bulletlist: [],
	    enermylist: [],
	    score: 0,
	    scores: [],
	    users: [],
	    showRank: false,
	    addscore: 0,
	    isShowDialog: false,
	    dialogTitle: 'HELLO',
	    dialogBody: 'Weex is best!',
	    comments: '',
	    addscorebottom: -100,
	    addscoreleft: -100,
	    video: {
	      src: 'http://gslb.miaopai.com/stream/iK8YPMJwHez-ot-OqVAWDA__.mp4?vend=miaopai&',
	      play_video: 'pause'
	    },
	    music: {
	      play: true
	    }
	  }},
	  created: function created() {
	    this.$on('model1selected', function () {
	      this.c = 1;
	      this.selectedurl = this.a;
	      this.showModel = false;
	      this.isShowDialog = true;
	    }.bind(this));
	    this.$on('model2selected', function () {
	      this.c = 2;
	      this.selectedurl = this.b;
	      this.showModel = false;
	      this.isShowDialog = true;
	    }.bind(this));
	    storage.getItem('scores', function (e) {
	      if (e.data !== 'undefined') {
	        this.scores = e.data.split(',').map(function (item, index) {
	          if (index !== 0) return parseInt(item);else {
	            return parseInt(item.slice(1));
	          }
	        });
	      } else {
	        this.scores = [];
	      }
	    }.bind(this));
	    storage.getItem('users', function (e) {
	      if (e.data !== 'undefined') {
	        this.users = e.data.split(',').map(function (item, index) {
	          return item.replace(/(\[|\]|")/g, '');
	        });
	      } else {
	        this.users = [];
	      }
	    }.bind(this));
	  },
	  methods: {
	    model1selected: function model1selected() {
	      this.c = 1;
	      this.selectedurl = this.a;
	      this.showModel = false;
	      this.isShowDialog = true;
	    },
	    model2selected: function model2selected() {
	      this.c = 2;
	      this.selectedurl = this.b;
	      this.showModel = false;
	      this.isShowDialog = true;
	    },
	    video_fail: function video_fail() {
	      var modal = __weex_require__('@weex-module/modal');
	      modal.toast({
	        'message': '资源加载出错，请检查网络',
	        'duration': 3
	      });
	    },
	    handlemusicclick: function handlemusicclick() {
	      if (this.c == 1) {
	        this.video.src = this.a[11];
	      } else if (this.c == 2) {
	        this.selectedurl = this.b;
	      }
	      this.music.play = !this.music.play;
	      if (this.status === 'playing' && this.music.play === true) this.video.play_video = 'play';else {
	        this.video.play_video = 'pause';
	      }
	    },
	    music_load: function music_load() {},
	    onfinish: function onfinish() {
	      this.video.play_video = 'pause';
	      setTimeout(function () {
	        if (this.music.play) this.video.play_video = 'play';
	      }.bind(this), 500);
	    },
	    handleRank: function handleRank() {
	      this.handlePause();
	      this.showRank = !this.showRank;
	    },
	    handleRankClear: function handleRankClear() {
	      this.scores = [];
	      this.users = [];
	      storage.removeItem('scores', function (e) {});
	      storage.removeItem('users', function (e) {});
	    },
	    handleRankClose: function handleRankClose() {
	      this.handleStart();
	      this.showRank = false;
	    },
	    handlepanmove: function handlepanmove(event) {
	      if (this.status === 'playing') {
	        var tempX = event.changedTouches[0].screenX;
	        var tempY = 1350 - event.changedTouches[0].screenY;
	        if (tempX <= 0) {
	          this.left = 0;
	        } else if (tempX >= 670) {
	          this.left = 670;
	        } else {
	          this.left = tempX;
	        }
	        if (tempY <= 10) {
	          this.bottom = 10;
	        } else if (tempY >= 1310) {
	          this.bottom = 1310;
	        } else {
	          this.bottom = tempY;
	        }
	      }
	    },
	    handlePause: function handlePause() {
	      if (this.status === 'playing') {
	        this.status = 'pause';

	        clearInterval(timer2);
	        this.isShowDialog = true;
	        this.addscoreleft = -100;
	        this.addscorebottom = -100;
	        this.video.play_video = 'pause';
	      }
	    },
	    handleStart: function handleStart() {
	      if (this.status !== 'pause') {
	        this.oil.left = 750;
	        this.bulletlist = [];
	        this.enermylist = [];
	        this.score = 0;
	        index1 = 0;
	        index2 = 0;
	        this.left = 335;
	        this.bottom = 50;
	      }
	      this.isShowDialog = false;
	      this.status = 'playing';
	      clearInterval(timer2);
	      timer2 = setInterval(function () {
	        if (this.oil.left > 0) this.oil.left -= 1;
	        if (this.oil.left <= 300) {
	          this.oil.color = 'red';
	        } else {
	          this.oil.color = 'orange';
	        }
	        if (this.oil.left === 0) {
	          this.myclassname = 'hide';

	          clearInterval(timer2);
	          this.isShowDialog = true;
	          this.addscoreleft = -100;
	          this.addscorebottom = -100;
	          this.$vm('myplane').$emit('explore');
	          this.video.play_video = 'pause';
	          this.status = 'die';
	          this.dialog.die.reason = 2;
	          return;
	        }

	        temp++;temp2++;
	        for (var j = 0; j < this.enermylist.length; j++) {
	          var success = 0;
	          for (var i = 0; i < this.bulletlist.length; i++) {
	            if (this.enermylist[j].hit) break;
	            if (this.bulletlist[i].classname == 'hide') continue;

	            if (this.enermylist[j].left < this.bulletlist[i].left + 30 && this.enermylist[j].left + 50 > this.bulletlist[i].left && this.enermylist[j].bottom <= this.bulletlist[i].bottom + 30 && this.enermylist[j].bottom + 50 > this.bulletlist[i].bottom) {
	              this.bulletlist[i].classname = 'hide';
	              this.enermylist[j].hit = true;
	              clearTimeout(timer);
	              this.addscoreleft = this.enermylist[j].left;
	              this.addscorebottom = this.enermylist[j].bottom + 70;
	              if (this.enermylist[j].type === 3) this.oil.left = this.oil.left + 100 > 750 ? 750 : this.oil.left + 100;
	              this.$vm('enermy-' + this.enermylist[j].index).$emit('hit', { index: this.enermylist[j].index });
	              switch (this.enermylist[j].type) {
	                case 0:
	                  this.addscore = 10;break;
	                case 1:
	                  this.addscore = 100;break;
	                case 2:
	                  this.addscore = 50;break;
	                case 3:
	                  this.addscore = 10;break;
	                default:
	                  break;
	              }
	              this.score += this.addscore;
	              timer = setTimeout(function () {
	                this.addscoreleft = -100;
	                this.addscorebottom = -100;
	              }.bind(this), 300);
	              break;
	            }
	          }

	          if (this.enermylist[j].type !== 3 && !this.enermylist[j].hit && this.enermylist[j].left > this.left - 50 && this.enermylist[j].left < this.left + 80 && this.enermylist[j].bottom <= this.bottom + 30 && this.enermylist[j].bottom + 50 > this.bottom) {
	            this.myclassname = 'hide';

	            clearInterval(timer2);
	            this.isShowDialog = true;
	            this.addscoreleft = -100;
	            this.addscorebottom = -100;
	            this.$vm('myplane').$emit('explore');
	            this.video.play_video = 'pause';
	            this.status = 'die';
	            this.dialog.die.reason = 1;
	            var user_name;
	            if (this.scores.length < 5 || this.score > this.scores[4]) {
	              modal.prompt({
	                'message': '真厉害，进入前5啦，留下大名吧!',
	                'okTitle': 'yes',
	                'cancelTitle': 'cancel'
	              }, function (e) {
	                if (e.result == 'yes') {
	                  this.scores.push(this.score);
	                  this.users.push(e.data);

	                  bubbleSort(this.scores, this.users);
	                  this.scores = this.scores.slice(0, 5);
	                  this.users = this.users.slice(0, 5);
	                  storage.setItem('scores', this.scores, function (e) {});
	                  storage.setItem('users', this.users, function (e) {});
	                  this.showRank = true;
	                }
	              }.bind(this));
	            }
	          }
	        }

	        if (temp === 6) {
	          temp = 0;
	          this.bulletlist.push({ 'index': index1++, 'left': this.left + 25, 'bottom': this.bottom, 'classname': 'show' });
	          if (index1 >= 1000) index1 = 0;
	        }
	        if (temp2 === 12) {
	          temp2 = 0;
	          var x = Math.random();
	          var addleft;
	          if (this.c == 1) {
	            addleft = 25;
	          } else if (this.c == 2) {
	            addleft = 125;
	          }
	          if (x < 0.2) this.enermylist.push({ 'index': index2++, 'type': 1, 'left': Math.floor(Math.random() * 700) + addleft, 'bottom': 1200, 'hit': false });else if (x < 0.5) this.enermylist.push({ 'index': index2++, 'type': 2, 'left': Math.floor(Math.random() * 700) + addleft, 'bottom': 1200, 'hit': false });else if (x < 0.58) this.enermylist.push({ 'index': index2++, 'type': 3, 'left': Math.floor(Math.random() * 700) + addleft, 'bottom': 1200, 'hit': false });else {
	            this.enermylist.push({ 'index': index2++, 'type': 0, 'left': Math.floor(Math.random() * 700) + addleft, 'bottom': 1200, 'hit': false });
	          }
	          if (index2 >= 1000) index2 = 0;
	        }
	        this.bulletlist = this.bulletlist.filter(function (item) {
	          item.bottom += 10;
	          return item.bottom < 1350;
	        });

	        if (this.c == 1) {
	          this.enermylist = this.enermylist.filter(function (item) {
	            switch (item.type) {
	              case 0:
	                item.bottom -= 8;break;
	              case 1:
	                item.bottom -= 13;break;
	              case 2:
	                item.bottom -= 10;break;
	              case 3:
	                item.bottom -= 7;break;
	            }
	            return item.bottom > -70;
	          });
	        } else if (this.c == 2) {
	          this.enermylist = this.enermylist.filter(function (item) {
	            switch (item.type) {
	              case 0:
	                item.bottom -= 8;item.left -= 5;break;
	              case 1:
	                item.bottom -= 15;item.left -= 8;break;
	              case 2:
	                item.bottom -= 11;item.left -= 5;break;
	              case 3:
	                item.bottom -= 8;item.left -= 5;break;
	            }
	            return item.bottom >= -70 && item.left >= -50;
	          });
	        }
	        if (this.c === 1) {
	          this.backimgtop -= 5;
	          if (this.backimgtop <= -1395 * 2) {
	            this.backimgtop = 0;
	          }
	        }
	      }.bind(this), 50);

	      if (this.music.play) this.video.play_video = 'play';
	    },

	    closeDialog: function closeDialog(e) {
	      clearInterval(timer2);
	      this.isShowDialog = false;
	      this.showModel = true;
	      this.status = 'init';
	      this.c = '';
	      this.score = 0;
	      this.backimgtop = 0;
	      this.bulletlist = [];
	      this.enermylist = [];
	      this.myclassname = 'show';
	      this.left = 335;
	      temp = 0;
	      temp2 = 0;
	      index1 = 0;
	      index2 = 0;
	      this.video.play_video = 'pause';
	    }
	  }
	};}
	/* generated by weex-loader */


/***/ }
/******/ ]);